### ISSUE TITLE
Skip dataset download if file already exists locally

### ISSUE THREAD

**Issue by lewtun** [lewtun/dslectures#16]
Running `get_dataset(...)` more than once creates duplicate files in `data/` that is annoying when working locally. Using python's subprocess, it should be possible to access wget's no-clobber argument: https://stackoverflow.com/questions/4944295/skip-download-if-files-exist-in-wget

**Comment by lvwerra** [comment]
alternatively, we could just check if path exists and skip wget altogether.

**Comment by lvwerra** [comment]
i'll take care of it

**Comment by lewtun** [comment]
thanks! your solution would be simpler - we just need to make sure the key is the same name as the file we want to download
